apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeappdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homeapp
  template:
    metadata:
      labels:
        app: homeapp
    spec:
      containers:
        - name: homeapp
          image: IMAGE_NAME
          ports:
            - containerPort: 80
