apiVersion: v1
kind: Service
metadata:
  name: homeappservice
spec:
  type: NodePort
  selector:
    app: homeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
