apiVersion: v1
kind: Service
metadata:
  name: homeAppService
spec:
  type: NodePort
  selector:
    app: homeAppDeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
